# .cnb.yml
$:
  vscode:
    - docker:
        # 指定开发环境镜像，可以是任意可访问的镜像。
        # 如果 image 指定的镜像中已安装 code-server 代码服务，将使用单容器模式启动开发环境
        # 如果 image 指定的镜像中未安装 code-server 代码服务，将使用双容器模式启动开发环境
        # 如下镜像为 CNB 默认开发环境镜像，已安装代码服务，将使用单容器模式启动开发环境
        # 可按需替换为其他镜像
        image: docker.cnb.cool/sumu.k/docker-learning/node-env
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: 配置git
          script: |
            git config --global core.editor vim
            git config --global alias.mylog "log --graph --pretty=format:'%C(magenta)[%an]%C(reset) %C(red)%h%C(reset) : %C(green)%s%C(reset) %C(yellow)%d%C(reset) %C(blue)(%cd)%C(reset) ' --abbrev-commit --date=format:'%Y-%m-%d %H:%M:%S'"
        - name: 准备开发环境
          script: |
            pnpm install
            pnpm stub

main:
  push:
    - stages:
        - name: sync to sumumm'github
          image: tencentcom/git-sync
          imports: https://cnb.cool/sumu.m/secret-key/-/blob/main/pages.yaml
          settings:
            target_url: https://github.com/docs-site/vitepress-theme-mist.git
            auth_type: https
            username: sumumm
            password: ${GITHUB_CNB_SYNC}
            force: true