packages:
  - docs
  - packages/*
  - build
  - plugins/*

catalog:
  '@iconify/vue': ^5.0.0
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^2.0.10
  '@types/node': ^24.3.0
  gray-matter: 4.0.3
  js-yaml: ^4.1.0
  markdown-it-container: ^4.0.0
  picocolors: ^1.1.1
  rimraf: ^6.0.1
  sass: ^1.90.0
  tinyglobby: ^0.2.14
  vite: ^7.1.2
  vitepress: ^1.6.4
  vue: ^3.5.18

catalogs:
  mist-plugins:
    '@docs-site/vitepress-auto-nav-sidebar': ^1.0.4
    '@docs-site/vitepress-plugin-catalogue': ^1.0.5
    '@docs-site/vitepress-plugin-demo': ^1.0.1
    '@docs-site/vitepress-plugin-doc-analysis': ^1.0.2
    '@docs-site/vitepress-plugin-file-content-loader': ^1.0.3
    '@docs-site/vitepress-plugin-permalink': ^1.0.2
    '@docs-site/vitepress-plugin-sidebar-resolve': ^1.0.1
    '@docs-site/vitepress-plugin-md-h1': ^1.0.0
  vue:
    '@vue/compiler-core': ^3.5.18
    '@vue/compiler-dom': ^3.5.18
    '@vue/reactivity': ^3.5.18
    '@vue/runtime-core': ^3.5.18
    '@vue/runtime-dom': ^3.5.18
