packages:
  - docs
  - packages/*
  - build

catalog:
  '@iconify/vue': ^5.0.0
  rimraf: ^6.0.1
  sass: ^1.90.0
  vite: ^7.1.2
  vitepress: 1.6.4
  vue: ^3.5.18

catalogs:
  vue:
    '@vue/compiler-core': ^3.5.18
    '@vue/compiler-dom': ^3.5.18
    '@vue/reactivity': ^3.5.18
    '@vue/runtime-core': ^3.5.18
    '@vue/runtime-dom': ^3.5.18
