# .github/workflows/npm-publish.yml

name: Publish Package to npmjs

on:
  push:
    branches:
      - master # 仅在 master 分支的推送时触发
    tags:
      - 'v*' # 避免标签推送循环触发
  workflow_dispatch: # 允许从 GitHub Actions 页面手动触发

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写权限创建标签
      id-token: write # npm 发布需要 OIDC 令牌

    # 条件：仅当提交消息包含 [publish] 时才运行
    if: contains(github.event.head_commit.message, '[publish]')
    steps:
      # 步骤 1: 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整提交历史（需要访问历史标签）
          persist-credentials: true # 保留凭证用于后续推送

      - name: 打印相关路径
        run: | # | 为 yaml 的特定符号，其下可以使用多行文字。
          echo "当前路径为 $(pwd)"
          echo "工作路径为 ${{ github.workspace }}"
          echo "HOME路径为 $HOME"

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: |
          corepack enable
          pnpm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |
          pnpm stub
          pnpm build

      # 步骤 6: 发布到 npm
      - name: Publish to npm
        run: |
          cd dist/vitepress-theme-mist
          # 设置npm registry并配置认证
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          pnpm publish --access public --no-git-checks # 发布公开包
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_NPM }} # 使用个人访问令牌进行身份验证

      # 步骤 7: 创建并推送版本标签
      - name: Create and push version tag
        run: |
          # 从 package.json 获取版本号
          VERSION=$(node -p "require('./package.json').version")
          TAG_NAME="v$VERSION"  # 构造标签名 (v + 版本号)

          # 配置 Git 用户信息 (使用 GitHub Actions 机器用户)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 创建带注释的标签
          git tag -a $TAG_NAME -m "Release $TAG_NAME"

          # 推送标签到远程仓库
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动生成的 token
